### ISSUE TITLE
Add a link to MobiDetails

### ISSUE THREAD

**Issue by beboche** [LOVDnl/LOVD3#455]
Hi,
small reminder for the new link button to be added for MobiDetails (https://mobidetails.iurc.montp.inserm.fr/MD/).

the simplest way for you I believe would be to submit a `POST` request to MobiDetails API:
https://mobidetails.iurc.montp.inserm.fr/MD/api/variant/create_g

using the following parameters:

- variant_ghgvs: genomic description of the variant (hg38), e.g. NC_000001.11:g.40817273T>G
- gene_hgnc: HGNC gene name e.g. KCNQ4
- caller: 'browser' or 'api'
- api_key: your API key

Concerning the caller parameter, 
- if you use 'browser', the result will directly be the variant page (after annotation, typically 10s). To use this you need a mechanism that will open the post request e.g. in a new window
- if you use 'cli', you will get a json object with the mobidetails_id and its url:
```
{
  "mobidetails_id": 118,
  "url": "https://mobidetails.iurc.montp.inserm.fr/MD/variant/118"
}
```

### Tasks (@ifokkema)

- [x] We need to store the API key somewhere, update the data model, and `inc-upgrade.php`.
- [x] Update form to add and edit the API key.
- [x] Link to check for variant in MobiDetails needs to be sent over POST using Ajax to try to block crawlers to open the link.
- [x] Check if variant already exists using the API. If it doesn't exist, issue a POST form to ask the user to create it or not.
- [x] If the user wants to create the variant in MD, let them wait @ LOVD until MD replies. Use the "cli" argument.
- [x] When MD responds, open a new window to the variant in MD and close the dialog.
- [x] Double-check what happens when I make the same `POST` call and the variant already exists.

**Comment by ifokkema** [comment]
Thanks David!
I've added some tasks for me to the issue and I'll pick it up when I get the time!

**Comment by ifokkema** [comment]
Hi David,

I'm exploring the API to see how to best do this. I see the `create_g` method demands an hg38 description, which we may not always have. So I'm looking at the `create` method which allows a cDNA description to be sent. It seems to return HTML only (using swagger and curl). Is there a cli version for this? Otherwise, will `create_g` also support hg19?

**Comment by beboche** [comment]
Hi Ivo,

the `create_g` method indeed requires hg38. I can plan to extend to hg19. Concerning the `create` method, it should return a JSON object using the cli parameter. Then it should be a bug. Can you send me the test variant you used? Then I'll checked and let you know when it's fixed.

**Comment by ifokkema** [comment]
Ah, got it, thanks! In that case, swagger needs to be updated because there is no `caller` field there:
https://mobidetails.iurc.montp.inserm.fr/MDAPI/#/MDAPI%20Variants/post_api_variant_create

Using curl I got it to work now.

**Comment by beboche** [comment]
Ah sorry I'm checking the dev version of swagger. I might have forgotten to update the production. Sorry about that. I'll do it asap.

**Comment by ifokkema** [comment]
Cool, thanks! I've started the dev on linking to you.

**Comment by beboche** [comment]
Great news! The swagger should be ok now.

**Comment by ifokkema** [comment]
Hi David,

I want other LOVD instances to be able to link to MD as well, so LOVD needs to configure the API key. To test the given API key, currently, I am thinking to do so by requesting:

`https://mobidetails.iurc.montp.inserm.fr/MD/api/variant/create?variant_chgvs=api_key_test&api_key=<key_to_be_tested>&caller=cli`.

This will, however, cause an error on your side if the key works:
```json
{
  "mobidetails_error": "Malformed query api_key_test"
}
`

Will that bother you? Is there a better way of testing a given API key?

Sorry for all the questions ;)

**Comment by beboche** [comment]
This is fine. I can plan a better test later where you just submit your key. But you can use this for now.

**Comment by ifokkema** [comment]
Hi David, this is now completed and I have updated the GV shared LOVD3 instance with this new code!
