### ISSUE TITLE
Build GA4GH Data Connect API

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#518]
### Build GA4GH Data Connect API

LOVD3 needs a new API for full data sharing. Several solutions and data formats were considered, and the [GA4GH Data Connect Table API](https://github.com/ga4gh-discovery/data-connect) solution was chosen in combination with a [VarioML-JSON](https://github.com/VarioML/VarioML) payload.

#### Tasks
- [x] Until all details have been worked out, this API requires authentication.
- [x] Handle `GET`.
- [x] Handle `HEAD`.
- [x] Add `/api/v2/ga4gh` endpoint, forwarding to the Table API.
- [x] Add `/api/v2/ga4gh/tables` as a starting point for the table discovery.
- [x] List the `variants` table, using a VarioML-JSON-based data model.
- [x] Add `/api/v2/ga4gh/table/variants/info` URL.
- [x] Add `/api/v2/ga4gh/table/variants/data`, which should just refer to the first data page.
- [x] Data pages (pagination) should follow the `.../data:hg19:chr1:123456` format. This supports using static files.
- [x] Make sure that non-public entries will never be included.
- [x] Make sure that non-public fields will never be included, so check those settings.
- [x] Data without a license or with a non-compatible license should only share summary data.
- [x] Data should be able to be filtered on;
  - [ ] ~~License~~ (**postponed**, optional filter when authorized, take note of https://github.com/ga4gh-discovery/data-connect/issues/107)
    - [x] Filter excluding detailed data for `BY-ND;0` and `BY-NC-ND;0` should be always on, as this data can not be aggregated and shared by us (treat like not having a license at all - share summary data only).
    - [x] LOVD/varcache should identify itself to unhide ND licenses with additional permissions.
    - [x] When LOVD/varcache is not querying, also `BY-ND;1` and `BY-NC-ND;1` licensed data should not be shared in detail. Summary data only.
  - [x] Date last edited (optional filter using the `If-Modified-Since` HTTP header, take note of https://github.com/ga4gh-discovery/data-connect/issues/107)
- [x] Add `/service-info` URL.
- [x] Make sure the VarioML payload validates against the JSON Schema file (still to be developed for variant-centered views).
  - [x] Develop the JSON schema for variant-centered views: https://github.com/VarioML/VarioML/issues/20
- [x] Make sure the whole output validates according to the GA4GH standards.
  - [x] Find a JSON Schema for that, or request one.
- [x] Since this development has taken quite some time, revalidate when all is done and make sure we comply to [v.1.0.0](https://github.com/ga4gh-discovery/data-connect/releases/tag/1.0.0).
  - [x] Perhaps we should put the version somewhere?
