### ISSUE TITLE
Comment on transcript

### ISSUE THREAD

**Issue by rahulraj7007** [LOVDnl/LOVD3#77]
Dear Ivo,

I wanted to see if it is easy to add a comment section on the transcript page . As a transcript selected for a gene may not always be the longest one and may be selected on a different criteria, it would be advantageous to include some information on why the transcript was selected. At the moment I can't find a way to include this information on the transcript section( but possible on variant on transcript)

Warm regards,
Rahul

## Tasks
- [x] Adapt inc-sql-tables.php to include new column.
- [x] Adapt inc-upgrade.php to include new column.
- [x] Describe field in getForm() in object_transcripts.php (as an optional textarea, like other remarks fields).
- [x] Describe field in VE column list in object_transcripts.php.

**Comment by ifokkema** [comment]
Hi Rahul,
Thank you for your suggestion! I see your point. I think this could be a good addition in LOVD3. I'll discuss it with the team tomorrow, and I'll let you know.
Regards, Ivo

**Comment by ifokkema** [comment]
Hi Rahul,
We're adding this to our to do list for the release after the one of next week!
Regards,
Ivo

**Comment by rahulraj7007** [comment]
Hi Ivo,


Excellent... Thanks for that..


Warm regards,
Rahul
