### ISSUE TITLE
Use singular "they" everywhere instead of "he", or "he/she"

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#97]
LOVD itself, its documentation and its website use "he" or "he/she" when referring to users. It would be better to use singular "they" instead.
Also, LOVD uses "my" and "your" inconsistently; "your account" and "update your registration" vs "download all my data". This also needs to be made consistent.

## Tasks
- [ ] Update website to use singular "they"
- [ ] Update LOVD to use singular "they"
- [ ] Update manual to use singular "they"
- [ ] Update course documentation to use singular "they"
- [ ] Update LOVD to be consistent in "my" and "your"
- [ ] Update manual with new link names and possibly new screenshots
- [ ] Update course documentation with new link names and possibly new screenshots

**Comment by mkroon1** [comment]
@ifokkema Do you have a preference regarding "my" vs "your"?

**Comment by ifokkema** [comment]
(after discussion, decided to use "you" and "your" everywhere.
